id: IBF92E95F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T22:12:55+00:00'
last_modified: '2022-06-07T15:12:21.068374+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ74556
  title: བླ་མ་མཆོད་པའི་ཆོ་ག།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    92F3:
      image_group_id: I4CZ74558
      title: ''
      total_pages: 96
      order: 1
      base_file: 92F3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
