id: IBF92E95F
legacy_id: P001800
ocr_import_info:
  bdrc_scan_id: W4CZ74556
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T22:12:13'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T21:12:01.164368+00:00'
last_modified: 2022-09-04 05:12:06.944253
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ74556
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ74556
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བླ་མ་མཆོད་པའི་ཆོ་ག
  author: དགུ་རོང ༠༢་སྣ་ཚོགས་རང་གྲོལ།
statistics:
  ocr_word_mean_confidence_index: 0.6813305510849951
  ocr_word_median_confidence_index: 0.7200000286102295
quality: null
bases:
  I4CZ74558:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ74558
      total_pages: 96
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ74558.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6813305510849951
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
