id: P001800
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W4CZ74556
  title: བླ་མ་མཆོད་པའི་ཆོ་ག།
  author: ''
  volumes:
    2dead2cbc8d544efb4577a4306075bac:
      image_group_id: I4CZ74558
      title: ''
      volume_number: 1
      total_pages: 96
      base_file: v001.txt
